"""Registry of supported AI coding tools."""

from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class AITool:
    name: str
    dotdir: str
    company: str
    skills_subpath: str = "skills"
    popularity: int = 0  # 1-10 (GitHub stars, user base, market share)
    performance: int = 0  # 1-10 (SWE-bench, coding quality, capabilities)
    price: int = 0  # 1-10 (10 = cheapest / most free)
    icon_url: str = ""  # Local icon path (e.g. /static/icons/tool.png)
    ignore_file: str = ""  # Ignore file name (e.g. .claudeignore), empty if unsupported
    website_url: str = ""  # Official product website


# .data/ is our central skill storage (source of truth)
SOURCE_DOTDIR = ".data"

# .agents/ is always auto-injected (Codex skills standard)
AUTO_INJECT_TOOL = AITool("Codex CLI (agents)", ".agents", "OpenAI")

# All tools that the user can select (popular tools first)
_IC = "/static/icons/{}"

TOOLS: tuple[AITool, ...] = (
    # ── Top tier ──────────────────────────────────────────────
    AITool(
        "Claude Code",
        ".claude",
        "Anthropic",
        popularity=9,
        performance=10,
        price=5,
        icon_url=_IC.format("claude-code.png"),
        ignore_file=".claudeignore",
        website_url="https://claude.ai/download",
    ),
    AITool(
        "Cursor",
        ".cursor",
        "Anysphere",
        popularity=9,
        performance=9,
        price=6,
        icon_url=_IC.format("cursor.svg"),
        ignore_file=".cursorignore",
        website_url="https://www.cursor.com",
    ),
    AITool(
        "Windsurf",
        ".windsurf",
        "Codeium",
        popularity=7,
        performance=7,
        price=7,
        icon_url=_IC.format("windsurf.png"),
        ignore_file=".codeiumignore",
        website_url="https://windsurf.com",
    ),
    AITool(
        "GitHub Copilot",
        ".github",
        "GitHub",
        popularity=10,
        performance=8,
        price=7,
        icon_url=_IC.format("github-copilot.png"),
        ignore_file=".copilotignore",
        website_url="https://github.com/features/copilot",
    ),
    AITool(
        "Cline",
        ".cline",
        "Cline",
        popularity=8,
        performance=7,
        price=9,
        icon_url=_IC.format("cline.png"),
        ignore_file=".clineignore",
        website_url="https://cline.bot",
    ),
    AITool(
        "Roo Code",
        ".roo",
        "Roo Code",
        popularity=6,
        performance=7,
        price=9,
        icon_url=_IC.format("roo-code.png"),
        ignore_file=".rooignore",
        website_url="https://roocode.com",
    ),
    AITool(
        "Codex CLI",
        ".codex",
        "OpenAI",
        popularity=8,
        performance=8,
        price=6,
        icon_url=_IC.format("codex-cli.png"),
        ignore_file=".codexignore",
        website_url="https://github.com/openai/codex",
    ),
    AITool(
        "Gemini CLI",
        ".gemini",
        "Google",
        popularity=8,
        performance=8,
        price=10,
        icon_url=_IC.format("gemini-cli.png"),
        ignore_file=".geminiignore",
        website_url="https://github.com/google-gemini/gemini-cli",
    ),
    AITool(
        "Continue.dev",
        ".continue",
        "Continue",
        popularity=5,
        performance=6,
        price=9,
        icon_url=_IC.format("continue.png"),
        ignore_file=".continueignore",
        website_url="https://continue.dev",
    ),
    AITool(
        "Amp",
        ".amp",
        "Sourcegraph",
        popularity=4,
        performance=7,
        price=4,
        icon_url=_IC.format("amp.png"),
        ignore_file=".ampignore",
        website_url="https://ampcode.com",
    ),
    AITool(
        "Kiro",
        ".kiro",
        "Amazon AWS",
        popularity=5,
        performance=7,
        price=5,
        icon_url=_IC.format("kiro.png"),
        ignore_file=".kiroignore",
        website_url="https://kiro.dev",
    ),
    AITool(
        "Trae",
        ".trae",
        "ByteDance",
        popularity=6,
        performance=7,
        price=8,
        icon_url=_IC.format("trae.png"),
        ignore_file=".traeignore",
        website_url="https://trae.ai",
    ),
    AITool(
        "Junie AI Agent",
        ".junie",
        "JetBrains",
        popularity=4,
        performance=7,
        price=5,
        icon_url=_IC.format("junie.png"),
        ignore_file=".aiignore",
        website_url="https://www.jetbrains.com/junie/",
    ),
    AITool(
        "Augment Code",
        ".augment",
        "Augment",
        popularity=3,
        performance=7,
        price=4,
        icon_url=_IC.format("augment.png"),
        ignore_file=".augmentignore",
        website_url="https://www.augmentcode.com",
    ),
    # ── Others (alphabetical) ────────────────────────────────
    AITool(
        "AdaL CLI",
        ".adal",
        "SylphAI",
        popularity=2,
        performance=5,
        price=7,
        website_url="https://github.com/SylphAI-Inc/AdalFlow",
    ),
    AITool(
        "Google Antigravity IDE",
        ".agent",
        "Google",
        popularity=3,
        performance=6,
        price=6,
        icon_url=_IC.format("antigravity.png"),
        ignore_file=".geminiignore",
        website_url="https://idx.dev",
    ),
    AITool(
        "CodeBuddy",
        ".codebuddy",
        "Tencent",
        popularity=3,
        performance=6,
        price=6,
        icon_url=_IC.format("codebuddy.png"),
        website_url="https://codebuddy.ai",
    ),
    AITool(
        "Command Code",
        ".commandcode",
        "CommandCode AI",
        popularity=2,
        performance=5,
        price=7,
        website_url="https://github.com/command-code/cli",
    ),
    AITool(
        "Cortex Code CLI",
        ".cortex",
        "Snowflake",
        popularity=3,
        performance=6,
        price=6,
        icon_url=_IC.format("cortex.png"),
        website_url="https://cortex.snowflake.com",
    ),
    AITool(
        "Crush",
        ".crush",
        "Charmbracelet",
        popularity=5,
        performance=6,
        price=8,
        icon_url=_IC.format("crush.png"),
        ignore_file=".crushignore",
        website_url="https://github.com/charmbracelet/crush",
    ),
    AITool(
        "Factory (Droids)",
        ".factory",
        "Factory AI",
        popularity=3,
        performance=6,
        price=5,
        icon_url=_IC.format("factory.png"),
        website_url="https://www.factory.ai",
    ),
    AITool(
        "Goose",
        ".goose",
        "Block",
        popularity=6,
        performance=6,
        price=10,
        icon_url=_IC.format("goose.png"),
        ignore_file=".gooseignore",
        website_url="https://github.com/block/goose",
    ),
    AITool(
        "iFlow CLI",
        ".iflow",
        "iFlow AI",
        popularity=2,
        performance=5,
        price=7,
        website_url="https://github.com/iflow-ai/iflow",
    ),
    AITool(
        "Kilo Code",
        ".kilocode",
        "Kilo",
        popularity=4,
        performance=6,
        price=9,
        icon_url=_IC.format("kilo-code.png"),
        ignore_file=".kilocodeignore",
        website_url="https://kilocode.ai",
    ),
    AITool(
        "Kimi Code CLI",
        ".kimi",
        "Moonshot AI",
        popularity=3,
        performance=6,
        price=7,
        icon_url=_IC.format("kimi.png"),
        website_url="https://kimi.ai",
    ),
    AITool(
        "Kode CLI",
        ".kode",
        "shareAI-lab",
        popularity=2,
        performance=5,
        price=8,
        website_url="https://github.com/shareAI-lab/kode",
    ),
    AITool(
        "MCPJam",
        ".mcpjam",
        "MCPJam",
        popularity=2,
        performance=5,
        price=7,
        website_url="https://mcpjam.com",
    ),
    AITool(
        "Mux",
        ".mux",
        "Coder",
        popularity=3,
        performance=6,
        price=7,
        icon_url=_IC.format("mux.png"),
        website_url="https://github.com/coder/mux",
    ),
    AITool(
        "Neovate Code",
        ".neovate",
        "NeovateAI",
        popularity=2,
        performance=5,
        price=7,
        website_url="https://neovate.ai",
    ),
    AITool(
        "OpenCode",
        ".opencode",
        "SST",
        popularity=3,
        performance=6,
        price=8,
        icon_url=_IC.format("opencode.png"),
        ignore_file=".opencodeignore",
        website_url="https://github.com/sst/opencode",
    ),
    AITool(
        "OpenHands",
        ".openhands",
        "All Hands AI",
        popularity=7,
        performance=8,
        price=9,
        icon_url=_IC.format("openhands.png"),
        ignore_file=".openhandsignore",
        website_url="https://www.all-hands.dev",
    ),
    AITool(
        "Pi Coding Agent",
        ".pi",
        "badlogic",
        popularity=2,
        performance=5,
        price=8,
        icon_url=_IC.format("pi.png"),
        website_url="https://github.com/badlogic/pi-coding-agent",
    ),
    AITool(
        "Pochi",
        ".pochi",
        "TabbyML",
        popularity=2,
        performance=5,
        price=7,
        icon_url=_IC.format("pochi.png"),
        website_url="https://tabby.tabbyml.com",
    ),
    AITool(
        "Qoder IDE",
        ".qoder",
        "Alibaba",
        popularity=3,
        performance=6,
        price=6,
        icon_url=_IC.format("qoder.png"),
        ignore_file=".qoderignore",
        website_url="https://qoder.ai",
    ),
    AITool(
        "Qwen Coding",
        ".qwen",
        "Alibaba",
        popularity=4,
        performance=7,
        price=8,
        icon_url=_IC.format("qwen.png"),
        ignore_file=".qwenignore",
        website_url="https://github.com/QwenLM/Qwen-Agent",
    ),
    AITool(
        "Vibe",
        ".vibe",
        "Mistral AI",
        popularity=3,
        performance=7,
        price=7,
        icon_url=_IC.format("vibe.png"),
        website_url="https://github.com/mistralai/vibe",
    ),
    AITool(
        "Zencoder",
        ".zencoder",
        "Zencoder AI",
        popularity=2,
        performance=5,
        price=6,
        website_url="https://zencoder.ai",
    ),
)


def detect_tools(target_root: Path) -> list[AITool]:
    """Return tools whose dotdir already exists in target_root."""
    return [t for t in TOOLS if (target_root / t.dotdir).is_dir()]
